### ISSUE TITLE
ログイン機構の致命的なエラー

### ISSUE THREAD

**Issue by polyacetal** [noko1024/e-auto#14]
環境によってはpathの入力,idの入力およびpassの入力画面でコントロール不能となる致命的なエラーが発生しました
また、chromedriverを同一ディレクトリに保存して相対パスでの指定にするのはどうでしょうか？

**Comment by noko1024** [comment]
getpassは入っていますか？

**Comment by polyacetal** [comment]
gitのbashに入力していたためでした
コマンドプロンプトのほうだとちゃんと動作しました

**Comment by yugu0202** [comment]
一応詳しく知りたいんだけど
入力画面で止まるって言うのはパスの入力はできてIDで止まったり、パスの入力で止まったりとランダムな感じ？

**Comment by noko1024** [comment]
getpassの入力で止まってた

**Comment by yugu0202** [comment]
なるほどね、GitのBashだとgetpass使えない感じなのかな？

**Comment by noko1024** [comment]
そうみたい
[https://stackoverflow.com/questions/49858821/python-getpass-doesnt-work-on-windows-git-bash-mingw64](同様の例)が報告されてるね

**Comment by yugu0202** [comment]
避けられない感じか…
しょうがないかね…

**Comment by noko1024** [comment]
そこでの回避方法として
`alias python='winpty -Xallow-non-tty python.exe'`
とするらしい。
`alias python='winpty python.exe'`
だけだと

> ファイルにリダイレクトしようとすると別のエラーが発生します。

とのこと

**Comment by yugu0202** [comment]
[これ](https://stackoverflow.com/questions/49858821/python-getpass-doesnt-work-on-windows-git-bash-mingw64)の回答のやつやったらなんとかならんかね？

**Comment by noko1024** [comment]
そもそもコマンドプロンプト or PowerShellなら問題は発生しないから
対応する必要はないと思う

**Comment by yugu0202** [comment]
そうやね
