### ISSUE TITLE
ChromeDriverのPath設定に関する問題

### ISSUE THREAD

**Issue by noko1024** [noko1024/e-auto#15]

**Comment by noko1024** [comment]
`e-auto.py:21: DeprecationWarning: use options instead of chrome_options`
`browser = webdriver.Chrome("chromedriver_path",chrome_options=options)`
`FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver_path'`

`During handling of the above exception, another exception occurred:`

`File "e-auto.py", line 21, in <module>`
`browser = webdriver.Chrome("chromedriver_path",chrome_options=options)`
`selenium.common.exceptions.WebDriverException: Message: 'chromedriver_path' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

一部抜粋ですが、上記のようなエラーを吐いています。

**Comment by yugu0202** [comment]
ごめんそれ
変数なのにストリングになってる

**Comment by polyacetal** [comment]
ストリングを変数に変えたら無事に動きました

**Comment by polyacetal** [comment]
僕はストリングをずっとintだと思って聞いてたので解決するまで理解できませんでした。
