### ISSUE TITLE
セットアップの自動化

### ISSUE THREAD

**Issue by noko1024** [noko1024/e-auto#22]
seleniumダウンロードからライブラリの構築まで行う

**Comment by noko1024** [comment]
- [x] seleniumダウンロード

- [ ] ライブラリの構築

**Comment by yugu0202** [comment]
とりあえずbs4,lxmlのダウンロード欲しい

**Comment by polyacetal** [comment]
exeファイルにして配布すれば解決では？

**Comment by noko1024** [comment]
パッケージングはリリース時にじゃない？
あと、周囲の依存環境が結構めんどい。
Chromiumにしろ

**Comment by yugu0202** [comment]
#23
**未対応バージョンの処理を追加しました**

**Comment by yugu0202** [comment]
#24
エラーの修正をしました
